import os
import time
import json
import requests
import telebot

# Telegram Bot Token (RAILWAY ENV)
BOT_TOKEN = os.getenv("BOT_TOKEN")

# Lookup API (No key needed)
LOOKUP_API = "https://numapi.anshapi.workers.dev/?num="

# Telegram Bot Init
bot = telebot.TeleBot(BOT_TOKEN)


# ======== CYBER BYTES BANNER ========
BANNER = r"""
╔═══════════════════════════════════════╗
║              CYBER BYTES              ║
║      Digital Security Intelligence     ║
╚═══════════════════════════════════════╝
"""


# ====== Remove external credit ======
def sanitize(data: dict):
    remove_keys = ["credit", "source", "api_owner", "developer"]
    for k in remove_keys:
        if k in data:
            data[k] = "Cyber Bytes Secure Database"
    return data


# ====== Hacker Loading Animation ======
def loading():
    stages = ["Initializing Scan",
              "Connecting to Cyber Bytes Database",
              "Fetching Intelligence",
              "Decoding Records",
              "Finalizing Report"]

    msg = "🔍 Starting Investigation...\n"
    for s in stages:
        msg += f"• {s}...\n"
        time.sleep(0.7)
    return msg


# ====== Build Investigation Report ======
def build_report(data, number):
    data = sanitize(data)

    report = f"""
{BANNER}

📂 **Investigation Report**
---------------------------------------

📞 **Target Number:** {number}
🛰️ **Scan Status:** Successful
🏢 **Data Source:** Cyber Bytes Secure Lookup System

---------------------------------------

🧾 **Subscriber Details**

• Registered Name : {data.get("name", "Not Available")}
• Father Name     : {data.get("fname", "Not Available")}
• Address         : {data.get("address", "Not Available")}
• Circle/State    : {data.get("circle", "Not Available")}
• Alternate No    : {data.get("alt_number", "Not Available")}
• Aadhar Linked   : {data.get("aadhar", "No Record")}
• ID Number       : {data.get("id_number", "Not Available")}

---------------------------------------

🛡️ **Report Generated By**
**Cyber Bytes — Digital Security Organization**
👤 Created By: *Nitesh Kumar Sah (Founder & CEO)*

---------------------------------------
⚠️ This report is auto‑generated from Cyber Bytes Secure Database.
"""

    return report


# ====== START COMMAND ======
@bot.message_handler(commands=['start'])
def start(message):
    bot.reply_to(
        message,
        f"{BANNER}\n"
        "🔐 *Welcome to Cyber Bytes Lookup Bot*\n\n"
        "Send any mobile number to generate an investigation report.\n"
        "Example: `9876543210`"
    )


# ====== NUMBER HANDLER ======
@bot.message_handler(func=lambda m: m.text.isdigit())
def lookup(message):
    number = message.text.strip()

    # Show Hacker Loading
    bot.reply_to(message, loading())

    try:
        response = requests.get(LOOKUP_API + number)
        data = response.json()

        final_report = build_report(data, number)
        bot.send_message(message.chat.id, final_report, parse_mode="Markdown")

    except Exception as e:
        bot.send_message(
            message.chat.id,
            f"❌ Error fetching data.\nDetails: {e}"
        )


# ====== RUN BOT ======
print("CYBER BYTES BOT RUNNING...")
bot.infinity_polling()
